#pragma once

#include <unordered_map>
#include <unordered_set>
#include <type_traits>
#include <string_view>
#include <stdexcept>
#include <coroutine>
#include <algorithm>
#include <optional>
#include <iostream>
#include <concepts>
#include <complex>
#include <variant>
#include <cstdint>
#include <numbers>
#include <numeric>
#include <utility>
#include <compare>
#include <bitset>
#include <string>
#include <vector>
#include <memory>
#include <ranges>
#include <cmath>
#include <tuple>
#include <span>
#include <bit>
#include <map>

#include "../include/EvoNDZ/util/platform.h"